In [1]:
import numpy as np


NUMPY EXERCISE 1


In [9]:
a=np.zeros(10)


In [11]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a1=np.ones(10)

In [15]:
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
a2=np.arange(10,50)

In [19]:
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
a3=np.arange(10,51,2)

In [23]:
a3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
a4=np.arange(0,9).reshape(3,3)

In [27]:
a4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
a5=np.identity(3)

In [31]:
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a6=np.random.normal(0,1,1)

In [45]:
a6

array([-0.03788525])

In [57]:
a7=np.random.normal(0,1,25)

In [59]:
a7

array([-0.63035988,  1.96678258, -0.50244162, -1.13821825, -0.67231232,
       -2.09972775,  0.15063936,  0.61994543, -0.67974056, -1.09751878,
       -0.06531923, -0.80629351, -0.5860352 , -1.81453229, -0.45578944,
       -0.98487031, -0.91830963,  0.16843312,  2.21679323,  0.81334546,
        0.19216492, -0.42592418,  0.57321201, -1.08749906,  0.10593819])

In [61]:
a8=np.linspace(0.01,1,100).reshape(10,10)

In [63]:
a8

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [65]:
a9=np.linspace(0,1,20)

In [67]:
a9

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [69]:
a10=np.arange(1,26).reshape(5,5)

In [71]:
a10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
a10[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [83]:
a10[3,4]

20

In [87]:
a10[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [89]:
a10[4,:]

array([21, 22, 23, 24, 25])

In [91]:
np.sum(a10)

325

In [93]:
np.sum(a10,axis =0)

array([55, 60, 65, 70, 75])

In [95]:
np.std(a10,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [97]:
np.var(a10,axis=1)

array([2., 2., 2., 2., 2.])

In [99]:
np.min(a10,axis=1)

array([ 1,  6, 11, 16, 21])

In [101]:
np.max(a10,axis=1)

array([ 5, 10, 15, 20, 25])

NUMPY EXERCISE 2


In [3]:
import numpy as np

In [5]:
a1=np.array([1,2,3])

In [7]:
a1

array([1, 2, 3])

In [11]:
a2=np.array([[1,2,4],[4,5,6]])

In [15]:
a2

array([[1, 2, 4],
       [4, 5, 6]])

In [35]:
a3 = np.array([[[1, 5, 2, 1],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],       
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [8, 3, 4, 0]]])            

In [37]:
a3

array([[[1, 5, 2, 1],
        [2, 3, 3, 5]],

       [[2, 2, 3, 1],
        [0, 1, 9, 1]],

       [[3, 1, 4, 2],
        [8, 3, 4, 0]]])

In [27]:
a1.dtype

dtype('int32')

In [29]:
a2.dtype

dtype('int32')

In [39]:
a3.dtype

dtype('int32')

In [41]:
a1.shape

(3,)

In [43]:
a2.shape

(2, 3)

In [47]:
a3.shape

(3, 2, 4)

In [49]:
a1.ndim

1

In [51]:
a2.ndim

2

In [53]:
a3.ndim

3

In [55]:
a4=np.zeros(12)

In [57]:
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
a5=np.ones(4).reshape(2,2)

In [63]:
a5

array([[1., 1.],
       [1., 1.]])

In [71]:
a6=np.random.randint(0,101,20)


In [73]:
a6

array([ 38,  58, 100,  70,  22,  62,  65,  18,  39,  24,  62,  50,  46,
        21,  69,   2,   5,  71,  76,  68])

In [75]:
np.sort(a6)

array([  2,   5,  18,  21,  22,  24,  38,  39,  46,  50,  58,  62,  62,
        65,  68,  69,  70,  71,  76, 100])

In [85]:
np.sort(a6)

array([  2,   5,  18,  21,  22,  24,  38,  39,  46,  50,  58,  62,  62,
        65,  68,  69,  70,  71,  76, 100])

In [89]:
 np.sort(a6)[::-1]

array([100,  76,  71,  70,  69,  68,  65,  62,  62,  58,  50,  46,  39,
        38,  24,  22,  21,  18,   5,   2])

In [93]:
a7=np.arange(0,25).reshape(5,5)

In [95]:
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
da=a7[2:,1:].copy

In [113]:
da

<function ndarray.copy>

In [137]:
a8=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [139]:
a8

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [147]:
a9=np.array([[5,6,7]])

In [125]:
a9

array([5, 6, 7])

In [153]:
a10=np.concatenate([a8,a9])

In [159]:
a10

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [161]:
np.hsplit(a10,3)

[array([[1],
        [3],
        [5],
        [5]]),
 array([[2],
        [4],
        [6],
        [6]]),
 array([[3],
        [5],
        [7],
        [7]])]

In [163]:
np.vsplit(a10,2)

[array([[1, 2, 3],
        [3, 4, 5]]),
 array([[5, 6, 7],
        [5, 6, 7]])]

In [165]:
a11=np.identity(4)


In [167]:
a11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [171]:
a11+ 4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [189]:
a12=np.random.normal(0,1,10)

In [191]:
a12

array([-0.42376382,  2.0164238 , -0.1502156 , -0.51877437, -0.21083127,
       -1.24338929, -0.08029116, -0.99438161,  0.70104322,  0.18111102])

In [193]:
a13=np.random.randint(0,25,(5,5))

In [195]:
a13

array([[ 7,  1, 15, 14, 10],
       [12, 20,  7,  5,  1],
       [ 8, 16, 21,  6,  3],
       [ 9, 17, 18, 20,  2],
       [ 4, 10,  8,  5,  4]])

In [197]:
np.min(a13,axis=0)

array([4, 1, 7, 5, 1])

In [199]:
np.max(a13,axis=0)

array([12, 20, 21, 20, 10])

In [201]:
np.var(a13,axis=0)

array([ 6.8 , 45.36, 30.16, 36.4 , 10.  ])

In [203]:
np.std(a13,axis=0)

array([2.60768096, 6.7349833 , 5.49181209, 6.03324125, 3.16227766])

In [205]:
a15=np.arange(100,151)

In [207]:
a15

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [217]:
a15[::,-1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [219]:
a17=np.random.randint(0,24,(5,5))

In [221]:
a17

array([[20, 13,  4, 11, 16],
       [ 4, 11, 21,  4,  2],
       [23, 13,  9, 14,  8],
       [ 9, 19, 20, 13, 21],
       [ 7, 19, 13,  3, 23]])

In [211]:
a16=np.array([1,0,2,0,0,4,0,8])

In [278]:
a18=np.ones(100).reshape(10,10)

In [280]:
a18

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [282]:
a18[1:9,1:9]=0

In [284]:
a18

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [330]:
a19=np.zeros((8,8))

In [332]:
a19

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [334]:
a19[1::2,::2]=1

In [336]:
a19[::2,1::2]=1

In [338]:
a19

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [328]:
a19

array([[1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [306]:
a20=np.random.randint(0,8,(3,3))

# 

In [308]:
a20

array([[6, 5, 1],
       [0, 0, 1],
       [6, 0, 0]])

In [310]:
a21=np.random.randint(0,8,(3,3))

In [312]:
a21

array([[0, 0, 4],
       [5, 4, 4],
       [6, 4, 2]])

In [314]:
a21+a20

array([[ 6,  5,  5],
       [ 5,  4,  5],
       [12,  4,  2]])

In [316]:
a20*a21

array([[ 0,  0,  4],
       [ 0,  0,  4],
       [36,  0,  0]])

In [318]:
a20-a21

array([[ 6,  5, -3],
       [-5, -4, -3],
       [ 0, -4, -2]])

<built-in method copy of numpy.ndarray object at 0x000001C99EA0F4B0>


<function ndarray.copy>